### PR TITLE
Support `axum` v0.7 through `axum-core` v0.4 and `http` v1

### LINKED ISSUE #402: Bump axum-core to 0.4
axum-core had a major version change with their 0.7 release.

### PR DESCRIPTION
**Pull request by vidhanio**
closes #402

### CODE REVIEW

**Comment by vidhanio** [comment]
8th time's the charm i guess, LOL

**Comment by philipcristiano** [comment]
@lambda-fairy are you able to take a look?

**Comment by evgenykobz** [comment]
Apparently, this breaking change broke the latest v. of Maud:

> breaking: The response returned by IntoResponse::into_response must use axum::body::Body as the body type. axum::response::Response does this.

**Comment by vidhanio** [comment]
> Apparently, this breaking change broke the latest v. of Maud:
> 
> > breaking: The response returned by IntoResponse::into_response must use axum::body::Body as the body type. axum::response::Response does this.

not just that. it's a semver-incompatible version bump which means the types are no longer compatible across projects with `axum` `0.6` as their dep vs `axum` `0.7`.

**Comment by jryio** [comment]
Likewise. I am currently pulling the forked branch into my project(s) to use with axum 0.7 (everything is working correctly so far) - thanks!

**Comment by lambda-fairy** [comment]
Thanks for the patience!

**Comment by philipcristiano** [comment]
@lambda-fairy any chance you could release a new version to crates.io now that this has been merged?

**Comment by lambda-fairy** [comment]
@philipcristiano I'll likely get to it this weekend. In the meantime, using a git dependency (like you've done) is good and supported.

I've been thinking about the literals-in-attribute-names proposal (#396 + #398). I don't feel comfortable releasing that in its current state. I want to collect my thoughts and decide whether to revert or polish that up first.

**Comment by jryio** [comment]
Grateful for your work on this crate @lambda-fairy! Thank you!

**Comment by lambda-fairy** [comment]
https://crates.io/crates/maud/0.26.0

**Pull request merged**
