### PR TITLE
Bump axum-core to 0.3.0

### PR DESCRIPTION
**Pull request by davidpdrsn**
This is required for axum 0.6 support

### CODE REVIEW

**Review by lambda-fairy — CHANGES_REQUESTED** [review]
Thanks for the PR!

Would you like to update the changelog and doctests as well? You can use #337 as an example.

**Comment by dsaghliani** [comment]
The doctest is failing because the `axum` dependency in `doctest/Cargo.toml` has to be updated to "0.6". Tweak that and it should work.

**Comment by kotx** [comment]
Any estimate on when this may be ready?

**Comment by davidpdrsn** [comment]
@lambda-fairy sorry for the delay. I've updated the changelog and fixed the doc tests now.

**Review by lambda-fairy — APPROVED** [review]

**Comment by lambda-fairy** [comment]
Thanks!

**Pull request merged**
