### PR TITLE
Upgrade syn to 1.0.8. Upgrade matches to 0.1.8

### LINKED ISSUE #178: Upgrade to syn 1.0
With `syn` 1.0 release, a upgrade would be great.

### PR DESCRIPTION
**Pull request by AlterionX**
Closes #178 

Not much needed to be done? I ran cargo test and all the tests passed, so I think that it's fine. Not entirely sure if that was all that needed to be done, however.

### CODE REVIEW

**Comment by AlterionX** [comment]
I'm trying to understand why the test failed, but, as far as I can tell, it seems to be failing inside a dependency? I don't know how that can happen.

**Comment by lambda-fairy** [comment]
That is indeed mysterious.

It's failing on `master` as well, so it shouldn't be an issue with your changes.

**Comment by lambda-fairy** [comment]
I [fixed the build](https://travis-ci.org/lambda-fairy/maud/builds/616134104) by [updating the benchmarks' dependencies](https://github.com/lambda-fairy/maud/commit/da20d192329424892f67735b637af669d36bc3c3).

@AlterionX can you please rebase your changes on top of the latest `master`?

You can verify the fix as follows:

```
cd benchmarks
cargo bench --no-run
```

This should modify the `Cargo.lock` as well -- please commit the updated file.

**Comment by AlterionX** [comment]
I think it worked this time :smile:.

**Comment by lambda-fairy** [comment]
Thanks!

**Pull request merged**
