### PR TITLE
Added #![feature(proc_macro_mixed_site)] for build fix

### PR DESCRIPTION
**Pull request by madmaxio**

### CODE REVIEW

**Comment by lambda-fairy** [comment]
Are you on the latest nightly? The latest build [passes](https://travis-ci.org/github/lambda-fairy/maud/builds/699714433) so I'm not sure what you're fixing here.

**Comment by madmaxio** [comment]
Right, lastest nightly failes for me.

**Comment by lambda-fairy** [comment]
Can you please run `rustc --version` and `cargo --version`?

**Comment by madmaxio** [comment]
Ah, looks like it was some version misconception, my bad.

**Pull request closed without merging**
